version: 1.10.0.{build}
branches:
  only:
  - master
max_jobs: 4
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x64
- Win32
environment: {}
build:
  project: googletest\msvc\2019\gtest.sln
  parallel: true
  verbosity: normal
test_script:
- cmd: 'C:\projects\googletest\googletest\msvc\2019\./../../output/windows/vs/v142/x64/Debug/gtest_unittest.exe --gtest_output=xml:.\gtest_UT_%CONFIGURATION%_%PLATFORM%.xml'
on_finish:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\gtest_UT_$($env:CONFIGURATION)_$($env:PLATFORM).xml))
artifacts:
- path: googletest\output
  name: googletest_binaries_$(Configuration)_$(Platform)-$(appveyor_build_version)
- path: googletest\include
  name: googletest_include-$(appveyor_build_version)
deploy:
- provider: GitHub
  tag: release-$(appveyor_build_version)
  auth_token:
    secure: FL0q/kJ4tkpO7htGNFPeOMdG3nhWjvNWQ98NtvtWbChJUYL82dpnbokqq91Oga/I
  repository: munsingh/googletest
  artifact: googletest_binaries_$(Configuration)_$(Platform)-$(appveyor_build_version),googletest_include-$(appveyor_build_version)
  draft: false
  prerelease: false
  force_update: false