version: 1.8.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
- Debug_DLL
- Release_DLL
platform:
- x64
- Win32
environment: {}
build:
  project: googletest\msvc\2017\gtest.sln
  parallel: true
  verbosity: normal
artifacts:
- path: googletest\output
  name: googletest_binaries_$(Configuration)_$(Platform)-$(appveyor_build_version)
- path: googletest\include
  name: googletest_include-$(appveyor_build_version)
deploy:
- provider: GitHub
  tag: release-$(appveyor_build_version)
  auth_token:
    secure: ksa5FON/JQjPZaLLzw5r0xLyPTJb3IwhWlaXg5NY3pJbeUF3q/3INpIveaZZ5Noc
  repository: munsingh/googletest
  artifact: googletest_binaries_$(Configuration)_$(Platform)-$(appveyor_build_version),googletest_include-$(appveyor_build_version)
  draft: false
  prerelease: false
force_update: false